#!/usr/bin/env node

import { randomBytes } from "node:crypto";
import { chmod, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { loadEnvFile } from "node:process";
import { pathToFileURL } from "node:url";
import { parseArgs } from "node:util";
import { createOfferRevocation, FiberOffersClient } from "@fiber-offers/sdk";

const optionDefinitions = {
  "api-key": { type: "string" },
  "asset-type": { type: "string", default: "ckb" },
  amount: { type: "string" },
  "amount-max": { type: "string" },
  "amount-min": { type: "string" },
  description: { type: "string" },
  "env-file": { type: "string", default: ".env" },
  expiry: { type: "string" },
  force: { type: "boolean", default: false },
  "fiber-rpc-url": { type: "string" },
  help: { type: "boolean", short: "h", default: false },
  "keys-dir": { type: "string" },
  "local-only": { type: "boolean", default: false },
  network: { type: "string", default: "testnet" },
  reason: { type: "string" },
  "resolver-url": { type: "string" },
  "single-use": { type: "boolean", default: false },
  symbol: { type: "string", default: "CKB" },
  username: { type: "string" }
};

export async function main(argv = process.argv.slice(2), runtime = {}) {
  const cwd = runtime.cwd ?? process.cwd();
  const stdout = runtime.stdout ?? process.stdout;
  const fetchImpl = runtime.fetchImpl ?? globalThis.fetch;
  const parsed = parseArgs({ args: argv, options: optionDefinitions, allowPositionals: true, strict: true });
  const [command, id] = parsed.positionals;
  const options = parsed.values;

  if (!command || options.help || command === "help") {
    stdout.write(helpText());
    return;
  }

  const envPath = resolve(cwd, options["env-file"]);
  if (command !== "init") loadOptionalEnv(envPath);
  const config = configuration(options, cwd);

  if (command === "init") return initCommand(options, { cwd, stdout, envPath });
  if (command === "doctor") return doctorCommand(config, { stdout, fetchImpl });
  if (command === "create") return createCommand(options, config, { stdout, fetchImpl });
  if (command === "register") return registerCommand(requiredId(id), config, { stdout, fetchImpl });
  if (command === "list") return listCommand(config, { stdout, fetchImpl });
  if (command === "revoke") return revokeCommand(requiredId(id), options, config, { stdout, fetchImpl });

  throw cliError(`unknown command: ${command}`, "UNKNOWN_COMMAND");
}

async function initCommand(options, context) {
  const resolverUrl = normalizeUrl(options["resolver-url"] ?? "http://127.0.0.1:8787", "resolver URL");
  const fiberRpcUrl = normalizeUrl(options["fiber-rpc-url"] ?? "http://127.0.0.1:8227", "Fiber RPC URL");
  const fiberUrl = new URL(fiberRpcUrl);
  if (fiberUrl.protocol !== "http:") {
    throw cliError("the default Docker relay requires an http Fiber RPC URL", "UNSUPPORTED_FIBER_RPC_URL");
  }
  const content = [
    "# Generated by fiber-offers init. Keep this file private.",
    `POSTGRES_PASSWORD=${secret(32)}`,
    `RESOLVER_API_KEY=${secret(32)}`,
    `RESOLVER_SECRET_ENCRYPTION_KEY=${secret(48)}`,
    `RESOLVER_PUBLIC_URL=${resolverUrl}`,
    "FIBER_INVOICE_MODE=fiber-rpc",
    `FIBER_RPC_HOST=${fiberUrl.hostname}`,
    `FIBER_RPC_PORT=${fiberUrl.port || "80"}`,
    `FIBER_HOST_RPC_URL=${fiberRpcUrl}`,
    ""
  ].join("\n");

  try {
    await writePrivateFile(context.envPath, content, { force: options.force });
  } catch (error) {
    if (error.code === "EEXIST") {
      throw cliError(`${context.envPath} already exists; use --force only when rotating a new or intentionally reset deployment`, "CONFIG_ALREADY_EXISTS");
    }
    throw error;
  }
  const keysDir = resolve(context.cwd, options["keys-dir"] ?? ".fiber-offers/keys");
  await mkdir(keysDir, { recursive: true, mode: 0o700 });
  await chmod(keysDir, 0o700);
  await writePrivateFile(resolve(dirname(keysDir), ".gitignore"), "*\n", { force: true, mode: 0o600 });
  print(context.stdout, {
    ok: true,
    env_file: context.envPath,
    keys_directory: keysDir,
    resolver_url: resolverUrl,
    fiber_rpc_url: fiberRpcUrl,
    next: [
      "docker compose up -d --build",
      "npm run cli -- doctor",
      "npm run cli -- create --description 'My offer' --amount 100000000 --username merchant"
    ]
  });
}

async function doctorCommand(config, context) {
  const [health, nodeBody] = await Promise.all([
    jsonRequest(context.fetchImpl, `${config.resolverUrl}/health`),
    jsonRequest(context.fetchImpl, config.fiberRpcUrl, {
      method: "POST",
      body: { jsonrpc: "2.0", id: "fiber-offers-doctor", method: "node_info", params: [] }
    })
  ]);
  const node = nodeBody.result;
  if (!node?.pubkey) throw cliError("Fiber node_info did not return pubkey", "FIBER_NODE_ID_UNAVAILABLE");
  const resolverNode = health.dependencies?.invoice_source?.node_id;
  const sameNode = !resolverNode || resolverNode === node.pubkey;
  const ready = health.ok === true && sameNode;
  print(context.stdout, {
    ok: ready,
    resolver_url: config.resolverUrl,
    resolver_healthy: health.ok === true,
    fiber_rpc_url: config.fiberRpcUrl,
    fiber_node_id: node.pubkey,
    resolver_node_id: resolverNode,
    same_node: sameNode,
    peers: hexNumber(node.peers_count),
    channels: hexNumber(node.channel_count)
  });
  if (!ready) throw cliError("resolver and Fiber node are not ready", "DOCTOR_CHECK_FAILED");
}

async function createCommand(options, config, context) {
  if (!options.description) throw cliError("--description is required", "MISSING_DESCRIPTION");
  const pricing = pricingOptions(options);
  const client = resolverClient(config, context.fetchImpl);
  const created = await client.createOffer(
    {
      resolver_url: config.resolverUrl,
      description: options.description,
      network: options.network,
      assets: [{ asset_type: options["asset-type"], symbol: options.symbol }],
      ...pricing,
      ...(options.expiry ? { expiry: positiveInteger(options.expiry, "expiry") } : {}),
      single_use: options["single-use"]
    },
    { fiberRpcUrl: config.fiberRpcUrl, fetchImpl: context.fetchImpl }
  );
  const keyPath = keyFile(config.keysDir, created.offer.offer_id);
  await writePrivateJson(keyPath, {
    version: 1,
    offer_id: created.offer.offer_id,
    offer: created.offer,
    encoded_offer: created.encoded_offer,
    offer_private_key_pem: created.offer_private_key_pem,
    username: options.username,
    resolver_url: config.resolverUrl,
    created_at: new Date().toISOString()
  });

  let registered;
  if (!options["local-only"]) {
    try {
      registered = await client.registerOffer(created.offer, { username: options.username });
    } catch (error) {
      error.message = `${error.message}; lifecycle key was preserved at ${keyPath}. Retry with: npm run cli -- register ${created.offer.offer_id}`;
      throw error;
    }
  }
  print(context.stdout, {
    ok: true,
    offer_id: created.offer.offer_id,
    node_id: created.offer.node_id,
    key_file: keyPath,
    registered: Boolean(registered),
    payment_link: registered?.payment_link,
    fiber_address: registered?.fiber_address
  });
}

async function registerCommand(offerId, config, context) {
  const record = await readKeyRecord(config.keysDir, offerId);
  const registered = await resolverClient(config, context.fetchImpl).registerOffer(record.offer, { username: record.username });
  print(context.stdout, {
    ok: true,
    offer_id: offerId,
    registered: true,
    payment_link: registered.payment_link,
    fiber_address: registered.fiber_address
  });
}

async function listCommand(config, context) {
  const result = await resolverClient(config, context.fetchImpl).listOffers();
  print(context.stdout, { ok: true, count: result.offers.length, offers: result.offers });
}

async function revokeCommand(offerId, options, config, context) {
  const record = await readKeyRecord(config.keysDir, offerId);
  const revocation = createOfferRevocation(record.offer, record.offer_private_key_pem, { reason: options.reason });
  const result = await resolverClient(config, context.fetchImpl).revokeOffer(offerId, revocation);
  print(context.stdout, { ok: true, ...result });
}

function configuration(options, cwd) {
  return {
    resolverUrl: normalizeUrl(options["resolver-url"] ?? process.env.RESOLVER_PUBLIC_URL ?? "http://127.0.0.1:8787", "resolver URL"),
    fiberRpcUrl: normalizeUrl(
      options["fiber-rpc-url"] ?? process.env.FIBER_HOST_RPC_URL ?? `http://${process.env.FIBER_RPC_HOST ?? "127.0.0.1"}:${process.env.FIBER_RPC_PORT ?? "8227"}`,
      "Fiber RPC URL"
    ),
    apiKey: options["api-key"] ?? process.env.RESOLVER_API_KEY,
    keysDir: resolve(cwd, options["keys-dir"] ?? ".fiber-offers/keys")
  };
}

function resolverClient(config, fetchImpl) {
  return new FiberOffersClient({ resolverUrl: config.resolverUrl, apiKey: config.apiKey, fetchImpl });
}

function pricingOptions(options) {
  if (options.amount) return { amount_min: positiveAmount(options.amount), amount_max: positiveAmount(options.amount) };
  if (!options["amount-min"]) throw cliError("--amount or --amount-min is required", "MISSING_AMOUNT");
  return {
    amount_min: positiveAmount(options["amount-min"]),
    ...(options["amount-max"] ? { amount_max: positiveAmount(options["amount-max"]) } : {})
  };
}

async function readKeyRecord(keysDir, offerId) {
  try {
    return JSON.parse(await readFile(keyFile(keysDir, offerId), "utf8"));
  } catch (error) {
    if (error.code === "ENOENT") throw cliError(`lifecycle key was not found for ${offerId}`, "OFFER_KEY_NOT_FOUND");
    throw error;
  }
}

function keyFile(keysDir, offerId) {
  if (!/^0x[0-9a-f]{64}$/.test(offerId)) throw cliError("offer_id must be 0x-prefixed sha256 hex", "INVALID_OFFER_ID");
  return resolve(keysDir, `${offerId}.json`);
}

async function writePrivateJson(path, value) {
  await mkdir(dirname(path), { recursive: true, mode: 0o700 });
  await chmod(dirname(path), 0o700);
  await writePrivateFile(path, `${JSON.stringify(value, null, 2)}\n`);
}

async function writePrivateFile(path, value, options = {}) {
  await mkdir(dirname(path), { recursive: true });
  const mode = options.mode ?? 0o600;
  if (!options.force) {
    await writeFile(path, value, { encoding: "utf8", flag: "wx", mode });
    return;
  }
  const temporary = `${path}.${process.pid}.tmp`;
  await writeFile(temporary, value, { encoding: "utf8", flag: "w", mode });
  await rename(temporary, path);
  await chmod(path, mode);
}

async function jsonRequest(fetchImpl, url, options = {}) {
  let response;
  try {
    response = await fetchImpl(url, {
      method: options.method ?? "GET",
      headers: { accept: "application/json", ...(options.body ? { "content-type": "application/json" } : {}) },
      body: options.body ? JSON.stringify(options.body) : undefined
    });
  } catch (error) {
    throw cliError(`cannot reach ${url}: ${error.message}`, "CONNECTION_FAILED");
  }
  const text = await response.text();
  const body = text ? JSON.parse(text) : undefined;
  if (!response.ok || body?.error) {
    throw cliError(body?.error?.message ?? `request failed with HTTP ${response.status}`, body?.error?.code ?? "REQUEST_FAILED");
  }
  return body;
}

function loadOptionalEnv(path) {
  try {
    loadEnvFile(path);
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
}

function normalizeUrl(value, name) {
  try {
    return new URL(value).toString().replace(/\/$/, "");
  } catch {
    throw cliError(`${name} must be an absolute URL`, "INVALID_URL");
  }
}

function positiveAmount(value) {
  if (!/^[1-9][0-9]*$/.test(String(value))) throw cliError("amounts must be positive integer strings", "INVALID_AMOUNT");
  return String(value);
}

function positiveInteger(value, name) {
  const parsed = Number(value);
  if (!Number.isSafeInteger(parsed) || parsed <= 0) throw cliError(`${name} must be a positive integer`, "INVALID_INTEGER");
  return parsed;
}

function requiredId(value) {
  if (!value) throw cliError("offer_id is required", "MISSING_OFFER_ID");
  return value;
}

function hexNumber(value) {
  return typeof value === "string" && value.startsWith("0x") ? Number.parseInt(value.slice(2), 16) : Number(value ?? 0);
}

function secret(bytes) {
  return randomBytes(bytes).toString("base64url");
}

function print(stdout, value) {
  stdout.write(`${JSON.stringify(value, null, 2)}\n`);
}

function cliError(message, code) {
  const error = new Error(message);
  error.code = code;
  return error;
}

function helpText() {
  return `Fiber Offers merchant CLI

Usage:
  fiber-offers init [--resolver-url URL] [--fiber-rpc-url URL]
  fiber-offers doctor
  fiber-offers create --description TEXT (--amount N | --amount-min N [--amount-max N]) [--username NAME]
  fiber-offers register OFFER_ID
  fiber-offers list
  fiber-offers revoke OFFER_ID [--reason TEXT]

Common options:
  --env-file PATH       Environment file to load (default: .env)
  --resolver-url URL    Public resolver URL
  --fiber-rpc-url URL   Host-reachable merchant FNN RPC URL
  --api-key KEY         Resolver management key (prefer RESOLVER_API_KEY)
  --keys-dir PATH       Lifecycle key directory (default: .fiber-offers/keys)
  -h, --help            Show this help
`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(JSON.stringify({ ok: false, error: { code: error.code ?? "CLI_ERROR", message: error.message } }, null, 2));
    process.exitCode = 1;
  });
}
